[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pda_limitation = "E5usXUWu4XR7rPJS6WLiYKWGj1BtUYLZL7TGc2mL78ZB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/solana-wallets/bob.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
