[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pda_limitation = "6Cjd4PNSWMyFbsA2MTXtEkxhnAgWzjDQV969kFjQJukL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/solana-wallets/bob.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
