[package]
name = "sign_pda_account"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.1.11"
solana-system-interface = "1.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
no-entrypoint = []
