[package]
name = "create_token_account_and_mint_example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
solana-client = "2.2"
solana-program = "2.2.1"
solana-sdk = "2.2"
spl-associated-token-account = "7.0"
spl-token = "8.0"
tokio = { version = "1.45", features = ["full"] }
